### ISSUE TITLE
No window appears when running kaktree-enable

### ISSUE THREAD

**Issue by SaphiraKai** [andreyorst/kaktree#9]
I don't know if it's bugged or if I'm just doing something wrong, but when I open kakoune and run `kaktree-enable`, no window appears. The new commands such as `kaktree-focus` do show up, but the tree itself is nowhere to be found.

I installed by cloning the repo to `~/.config/kak/autoload`, and haven't made any changes to my kakrc or anything else. I've checked that my `ls` supports all the mentioned options, and perl is installed. My kakoune is version `v2020.09.01`.

**Comment by andreyorst** [comment]
`kaktree-enable` only loads necessary things, and prepares kaktree. You need to call `kaktree-toggle` for it actually to show
